<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>attri_css_img_test_suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cd01a4a1-e6c4-4e6f-96b8-56e55fb0f913</testSuiteGuid>
   <testCaseLink>
      <guid>0b62fe2d-3e2d-405d-8f11-42160c7cb498</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Attributes/attribute_tc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c60bfd9-b794-4ff7-ac99-799956f8cf68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05873964-a00a-44cb-9903-c391f74d220b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98c47ed1-817f-4b8b-a7c8-dd576d7670f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Attributes/CSS_ATTRI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68bfb779-28c1-4700-9a0a-a8593077f023</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15f2c8b-c54f-4f3e-aed3-497ea6a8ca5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
