<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b7fda537-f567-4134-8135-613f00e74376</testSuiteGuid>
   <testCaseLink>
      <guid>bdb8a96d-53c8-4a77-9d49-df937b85d4ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7a0de101-180b-48bb-b83f-5fd62910e83b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dfiles/dfiles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7a0de101-180b-48bb-b83f-5fd62910e83b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>07a1cb8f-e4a9-40db-8e5c-a997d3f9ec20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7a0de101-180b-48bb-b83f-5fd62910e83b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>216e0d00-d4eb-4547-b7e8-fbe749f9f48e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f768c7a3-e2a8-4863-a19f-44488580512e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b2f00f89-8d0c-4b91-8a87-b15ddd7ca7ab</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dfiles/dfiles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b2f00f89-8d0c-4b91-8a87-b15ddd7ca7ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>202488d6-a131-4c5f-909a-a417994c1538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b2f00f89-8d0c-4b91-8a87-b15ddd7ca7ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>eea5d9e9-1c3c-45ee-a4b5-b21920e300e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf9095bc-516e-40dc-bc70-4c9860acac60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/desk_rec_TC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ca27ef9b-da88-42f7-850a-9eb9679b7ab3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Attributes/attribute_tc</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d406eefb-10f7-4be4-b7e1-c0302dd019ce</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/bind/bind_tcs</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d406eefb-10f7-4be4-b7e1-c0302dd019ce</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>9c60bfd9-b794-4ff7-ac99-799956f8cf68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d406eefb-10f7-4be4-b7e1-c0302dd019ce</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>05873964-a00a-44cb-9903-c391f74d220b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33fa1dc7-27eb-4faf-884e-9d7f9a677d7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Attributes/CSS_ATTRI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ef8e994-19bd-4224-b65b-646c738d8fff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/bind/bind_tcs</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7ef8e994-19bd-4224-b65b-646c738d8fff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>68bfb779-28c1-4700-9a0a-a8593077f023</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ef8e994-19bd-4224-b65b-646c738d8fff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>d15f2c8b-c54f-4f3e-aed3-497ea6a8ca5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>707fdaaf-f896-4520-a0a8-1446fc1779df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Attributes/img</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ecb7d6d8-a415-4e6f-877d-2e1fc9008355</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/bind/bind_tcs</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ecb7d6d8-a415-4e6f-877d-2e1fc9008355</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>a93c1cf9-e88f-4e6f-a418-b2cf1c85d65d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ecb7d6d8-a415-4e6f-877d-2e1fc9008355</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>cef40f38-43ea-4342-8e0e-7ac901d74d96</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
